/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "jp.co.sony.csl.dcoes.apis"
version = "3.9.14"
description = "APIS COMMON"

java.sourceCompatibility = JavaVersion.VERSION_11
java.targetCompatibility = JavaVersion.VERSION_11

dependencies {
    api(platform("jp.co.sony.csl.dcoes.apis:apis-bom:${project.version}"))
    api(libs.io.vertx.vertx.core)
    api(libs.org.slf4j.slf4j.api)
    api(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.io.vertx.vertx.unit)
    testImplementation(libs.junit.junit)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xlint:deprecation")
    options.isDeprecation = true
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
    (options as StandardJavadocDocletOptions).apply {
        author(true)
        showFromPrivate()
        addStringOption("Xdoclint:none", "-quiet")
    }
}